In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as pyplot
import seaborn as sns
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.float_format', lambda x: '{:.2f}'.format(x))
np.set_printoptions(suppress=True)

In [3]:
df_customers = pd.read_csv('/content/customers.csv')
df_loans = pd.read_csv('/content/bureau_data.csv')
df_bureau = pd.read_csv('/content/loans.csv')

In [4]:
df_customers.shape, df_loans.shape, df_bureau.shape

((50000, 12), (50000, 8), (50000, 15))

In [6]:
df_customers.head(3)

  cust_id  age gender  ...     city        state  zipcode
0  C00001   44      M  ...    Delhi        Delhi   110001
1  C00002   38      M  ...  Chennai   Tamil Nadu   600001
2  C00003   46      F  ...  Kolkata  West Bengal   700001

[3 rows x 12 columns]

In [7]:
df_loans.head(3)

  cust_id  number_of_open_accounts  ...  enquiry_count  credit_utilization_ratio
0  C00001                        1  ...              3                         7
1  C00002                        3  ...              5                         4
2  C00003                        2  ...              6                        58

[3 rows x 8 columns]

In [8]:
df_bureau.head(3)

  loan_id cust_id loan_purpose  ... disbursal_date  installment_start_dt  default
0  L00001  C00001         Auto  ...     2019-07-24            2019-08-10    False
1  L00002  C00002         Home  ...     2019-07-24            2019-08-15    False
2  L00003  C00003     Personal  ...     2019-07-24            2019-08-21    False

[3 rows x 15 columns]

In [10]:
df = pd.merge(df_customers, df_loans, on='cust_id')
df = pd.merge(df, df_bureau, on='cust_id')
df.head(3)

  cust_id  age gender  ... disbursal_date installment_start_dt  default
0  C00001   44      M  ...     2019-07-24           2019-08-10    False
1  C00002   38      M  ...     2019-07-24           2019-08-15    False
2  C00003   46      F  ...     2019-07-24           2019-08-21    False

[3 rows x 33 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cust_id                      50000 non-null  object
 1   age                          50000 non-null  int64
 2   gender                       50000 non-null  object
 3   marital_status               50000 non-null  object
 4   employment_status            50000 non-null  object
 5   income                       50000 non-null  int64
 6   number_of_dependants         50000 non-null  int64
 7   residence_type               49938 non-null  object
 8   years_at_current_address     50000 non-null  int64
 9   city                         50000 non-null  object
 10  state                        50000 non-null  object
 11  zipcode                      50000 non-null  int64
 12  number_of_open_accounts      50000 non-null  int64
 13  number_of_closed_accounts    50000 non-null  int64
 14  total_loan_months            50000 non-null  int64
 15  delinquent_months            50000 non-null  int64
 16  total_dpd                    50000 non-null  int64
 17  enquiry_count                50000 non-null  int64
 18  credit_utilization_ratio     50000 non-null  int64
 19  loan_id                      50000 non-null  object
 20  loan_purpose                 50000 non-null  object
 21  loan_type                    50000 non-null  object
 22  sanction_amount              50000 non-null  int64
 23  loan_amount                  50000 non-null  int64
 24  processing_fee               50000 non-null  float64
 25  gst                          50000 non-null  int64
 26  net_disbursement             50000 non-null  int64
 27  loan_tenure_months           50000 non-null  int64
 28  principal_outstanding        50000 non-null  int64
 29  bank_balance_at_application  50000 non-null  int64
 30  disbursal_date               50000 non-null  object
 31  installment_start_dt         50000 non-null  object
 32  default                      50000 non-null  bool
dtypes: bool(1), float64(1), int64(19), object(12)
memory usage: 12.3+ MB

In [12]:
df['default'] = df['default'].astype(int)
df.default.value_counts()

default
0    45703
1     4297
Name: count, dtype: int64

##### Due to the Data Leakage problem and Target Leakage problem, we are first split the data set.

In [13]:
X = df.drop('default', axis='columns')
y = df['default']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

df_train = pd.concat([X_train, y_train], axis='columns')
df_test = pd.concat([X_test, y_test], axis='columns')

df_train.head()

      cust_id  age gender  ... disbursal_date installment_start_dt  default
27434  C27435   45      F  ...     2022-04-21           2022-05-21        0
13400  C13401   29      M  ...     2020-11-24           2020-12-11        0
883    C00884   50      F  ...     2019-08-25           2019-09-19        0
7303   C07304   43      F  ...     2020-04-16           2020-05-05        0
45124  C45125   31      F  ...     2024-01-26           2024-02-17        0

[5 rows x 33 columns]

In [14]:
df_test.shape, df_train.shape

((12500, 33), (37500, 33))